# Generated by Django 2.0.4 on 2018-04-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semana_lince', '0002_auto_20180414_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('id',)},
        ),
    ]
