# Generated by Django 2.0.4 on 2018-04-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semana_lince', '0003_auto_20180414_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistance',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='responsable',
            options={'ordering': ('id',)},
        ),
    ]
